#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : axel
Version  : 2.17.9
Release  : 6
URL      : https://github.com/axel-download-accelerator/axel/releases/download/v2.17.9/axel-2.17.9.tar.xz
Source0  : https://github.com/axel-download-accelerator/axel/releases/download/v2.17.9/axel-2.17.9.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: axel-bin = %{version}-%{release}
Requires: axel-license = %{version}-%{release}
Requires: axel-locales = %{version}-%{release}
Requires: axel-man = %{version}-%{release}
BuildRequires : pkgconfig(openssl)

%description
# AXEL - Lightweight CLI download accelerator
## About
Axel tries to accelerate the download process by using multiple
connections per file, and can also balance the load between
different servers.

%package bin
Summary: bin components for the axel package.
Group: Binaries
Requires: axel-license = %{version}-%{release}

%description bin
bin components for the axel package.


%package license
Summary: license components for the axel package.
Group: Default

%description license
license components for the axel package.


%package locales
Summary: locales components for the axel package.
Group: Default

%description locales
locales components for the axel package.


%package man
Summary: man components for the axel package.
Group: Default

%description man
man components for the axel package.


%prep
%setup -q -n axel-2.17.9
cd %{_builddir}/axel-2.17.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1596516278
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1596516278
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/axel
cp %{_builddir}/axel-2.17.9/COPYING %{buildroot}/usr/share/package-licenses/axel/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
%make_install
%find_lang axel

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/axel

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/axel/06877624ea5c77efe3b7e39b0f909eda6e25a4ec

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/axel.1

%files locales -f axel.lang
%defattr(-,root,root,-)

